server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
      routes:
      - id: resell-bff
        uri: lb://resell-bff
        predicates:
        - Path=/resell-bff/**
      - id: resell-users
        uri: lb://resell-users
        predicates:
        - Path=/resell-users/**
      - id: resell-aouth
        uri: lb://resell-aouth
        predicates:
        - Path=/resell-aouth/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        sleuth:
          sampler:
            probability: 1.0